# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pythonProject\form2(uk).ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow")
        MainWindow2.resize(214, 485)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow2.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 168, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a1.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a1.setObjectName("a1")
        self.verticalLayout.addWidget(self.a1)
        self.a2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a2.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a2.setObjectName("a2")
        self.verticalLayout.addWidget(self.a2)
        self.a3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a3.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a3.setObjectName("a3")
        self.verticalLayout.addWidget(self.a3)
        self.a4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a4.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a4.setObjectName("a4")
        self.verticalLayout.addWidget(self.a4)
        self.a5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a5.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a5.setObjectName("a5")
        self.verticalLayout.addWidget(self.a5)
        self.a6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a6.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a6.setObjectName("a6")
        self.verticalLayout.addWidget(self.a6)
        self.a7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a7.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a7.setObjectName("a7")
        self.verticalLayout.addWidget(self.a7)
        self.a8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.a8.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(134, 202, 45, 1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.a8.setObjectName("a8")
        self.verticalLayout.addWidget(self.a8)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(10, 350, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.next_button.setFont(font)
        self.next_button.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.next_button.setObjectName("next_button")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 214, 26))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow", "Optimal food plan"))
        self.label.setText(_translate("MainWindow", "Оберіть алергени"))
        self.a1.setText(_translate("MainWindow", "Глютен"))
        self.a2.setText(_translate("MainWindow", "Лактоза"))
        self.a3.setText(_translate("MainWindow", "Молочні продукти"))
        self.a4.setText(_translate("MainWindow", "Яйця"))
        self.a5.setText(_translate("MainWindow", "Горіхи"))
        self.a6.setText(_translate("MainWindow", "Соя"))
        self.a7.setText(_translate("MainWindow", "Морепродукти"))
        self.a8.setText(_translate("MainWindow", "Нема"))
        self.next_button.setText(_translate("MainWindow", "Далі"))


if __name__ == "__main__":
    import sys
    app2 = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui2 = Ui_MainWindow()
    ui2.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
