# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pythonProject\form3(uk).ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 665)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(2000, 1000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(90, 290, 131, 247))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.monday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.monday.setFont(font)
        self.monday.setObjectName("monday")
        self.verticalLayout_8.addWidget(self.monday)
        self.tuesday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tuesday.setFont(font)
        self.tuesday.setObjectName("tuesday")
        self.verticalLayout_8.addWidget(self.tuesday)
        self.wednesday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wednesday.setFont(font)
        self.wednesday.setObjectName("wednesday")
        self.verticalLayout_8.addWidget(self.wednesday)
        self.thursday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thursday.setFont(font)
        self.thursday.setObjectName("thursday")
        self.verticalLayout_8.addWidget(self.thursday)
        self.friday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.friday.setFont(font)
        self.friday.setObjectName("friday")
        self.verticalLayout_8.addWidget(self.friday)
        self.saturday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saturday.setFont(font)
        self.saturday.setObjectName("saturday")
        self.verticalLayout_8.addWidget(self.saturday)
        self.sunday = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sunday.setFont(font)
        self.sunday.setObjectName("sunday")
        self.verticalLayout_8.addWidget(self.sunday)
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(310, 270, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.calculate.setFont(font)
        self.calculate.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.calculate.setObjectName("calculate")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 67, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 67, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 0, 139, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.age = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age.sizePolicy().hasHeightForWidth())
        self.age.setSizePolicy(sizePolicy)
        self.age.setObjectName("age")
        self.verticalLayout_2.addWidget(self.age)
        self.height = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height.sizePolicy().hasHeightForWidth())
        self.height.setSizePolicy(sizePolicy)
        self.height.setObjectName("height")
        self.verticalLayout_2.addWidget(self.height)
        self.weight = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight.sizePolicy().hasHeightForWidth())
        self.weight.setSizePolicy(sizePolicy)
        self.weight.setObjectName("weight")
        self.verticalLayout_2.addWidget(self.weight)
        self.activity = QtWidgets.QFontComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activity.sizePolicy().hasHeightForWidth())
        self.activity.setSizePolicy(sizePolicy)
        self.activity.setStyleSheet("Практично відсутня активність\n"
"Слабка активність\n"
"Середня активність\n"
"Висока активність\n"
"Екстримальна активність")
        self.activity.setObjectName("activity")
        self.verticalLayout_2.addWidget(self.activity)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(310, 170, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.add.setFont(font)
        self.add.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.add.setObjectName("add")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(250, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.help.setFont(font)
        self.help.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:15px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.help.setObjectName("help")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.monday.setText(_translate("MainWindow", "Понеділок"))
        self.tuesday.setText(_translate("MainWindow", "Вівторок"))
        self.wednesday.setText(_translate("MainWindow", "Середа"))
        self.thursday.setText(_translate("MainWindow", "Четвер"))
        self.friday.setText(_translate("MainWindow", "П\'ятниця"))
        self.saturday.setText(_translate("MainWindow", "Субота"))
        self.sunday.setText(_translate("MainWindow", "Неділя"))
        self.calculate.setText(_translate("MainWindow", "Розрахувати"))
        self.label_7.setText(_translate("MainWindow", "Ім\'я"))
        self.label.setText(_translate("MainWindow", "Вік"))
        self.label_3.setText(_translate("MainWindow", "Зріст"))
        self.label_4.setText(_translate("MainWindow", "Масса"))
        self.label_5.setText(_translate("MainWindow", "Активність"))
        self.label_2.setText(_translate("MainWindow", "Оберіть день, коли ви"))
        self.add.setText(_translate("MainWindow", "Додати члена родини"))
        self.help.setText(_translate("MainWindow", "?"))
        self.label_6.setText(_translate("MainWindow", " не можете обідами вдома"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
