# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pythonProject\form4(uk).ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 643)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name1 = QtWidgets.QLabel(self.centralwidget)
        self.name1.setGeometry(QtCore.QRect(220, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name1.setFont(font)
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QLabel(self.centralwidget)
        self.name2.setGeometry(QtCore.QRect(300, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name2.setFont(font)
        self.name2.setObjectName("name2")
        self.name3 = QtWidgets.QLabel(self.centralwidget)
        self.name3.setGeometry(QtCore.QRect(400, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name3.setFont(font)
        self.name3.setObjectName("name3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 50, 583, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView_2 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_2.addWidget(self.listView_2)
        self.listView_5 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_5.setObjectName("listView_5")
        self.verticalLayout_2.addWidget(self.listView_5)
        self.listView_6 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_6.setObjectName("listView_6")
        self.verticalLayout_2.addWidget(self.listView_6)
        self.listView_4 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_4.setObjectName("listView_4")
        self.verticalLayout_2.addWidget(self.listView_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listView_14 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_14.setObjectName("listView_14")
        self.verticalLayout_5.addWidget(self.listView_14)
        self.listView_15 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_15.setObjectName("listView_15")
        self.verticalLayout_5.addWidget(self.listView_15)
        self.listView_16 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_16.setObjectName("listView_16")
        self.verticalLayout_5.addWidget(self.listView_16)
        self.listView_17 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_17.setObjectName("listView_17")
        self.verticalLayout_5.addWidget(self.listView_17)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.listView_18 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_18.setObjectName("listView_18")
        self.verticalLayout_6.addWidget(self.listView_18)
        self.listView_19 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_19.setObjectName("listView_19")
        self.verticalLayout_6.addWidget(self.listView_19)
        self.listView_20 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_20.setObjectName("listView_20")
        self.verticalLayout_6.addWidget(self.listView_20)
        self.listView_21 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_21.setObjectName("listView_21")
        self.verticalLayout_6.addWidget(self.listView_21)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listView_22 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_22.setObjectName("listView_22")
        self.verticalLayout_7.addWidget(self.listView_22)
        self.listView_23 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_23.setObjectName("listView_23")
        self.verticalLayout_7.addWidget(self.listView_23)
        self.listView_24 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_24.setObjectName("listView_24")
        self.verticalLayout_7.addWidget(self.listView_24)
        self.listView_25 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_25.setObjectName("listView_25")
        self.verticalLayout_7.addWidget(self.listView_25)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listView_26 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_26.setObjectName("listView_26")
        self.verticalLayout_8.addWidget(self.listView_26)
        self.listView_27 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_27.setObjectName("listView_27")
        self.verticalLayout_8.addWidget(self.listView_27)
        self.listView_28 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_28.setObjectName("listView_28")
        self.verticalLayout_8.addWidget(self.listView_28)
        self.listView_29 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_29.setObjectName("listView_29")
        self.verticalLayout_8.addWidget(self.listView_29)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_10 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_10.setObjectName("listView_10")
        self.verticalLayout_4.addWidget(self.listView_10)
        self.listView_11 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_11.setObjectName("listView_11")
        self.verticalLayout_4.addWidget(self.listView_11)
        self.listView_12 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_12.setObjectName("listView_12")
        self.verticalLayout_4.addWidget(self.listView_12)
        self.listView_13 = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView_13.setObjectName("listView_13")
        self.verticalLayout_4.addWidget(self.listView_13)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.day = QtWidgets.QLabel(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(50, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.day.setFont(font)
        self.day.setObjectName("day")
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(190, 450, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.show.setFont(font)
        self.show.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.show.setObjectName("show")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(430, 510, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.next.setFont(font)
        self.next.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.next.setObjectName("next")
        self.prev = QtWidgets.QPushButton(self.centralwidget)
        self.prev.setGeometry(QtCore.QRect(190, 510, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.prev.setFont(font)
        self.prev.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;\n"
"")
        self.prev.setObjectName("prev")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 151, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView_3 = QtWidgets.QListView(self.layoutWidget)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_3.addWidget(self.listView_3)
        self.listView_7 = QtWidgets.QListView(self.layoutWidget)
        self.listView_7.setObjectName("listView_7")
        self.verticalLayout_3.addWidget(self.listView_7)
        self.listView_8 = QtWidgets.QListView(self.layoutWidget)
        self.listView_8.setObjectName("listView_8")
        self.verticalLayout_3.addWidget(self.listView_8)
        self.listView_9 = QtWidgets.QListView(self.layoutWidget)
        self.listView_9.setObjectName("listView_9")
        self.verticalLayout_3.addWidget(self.listView_9)
        self.name4 = QtWidgets.QLabel(self.centralwidget)
        self.name4.setGeometry(QtCore.QRect(490, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name4.setFont(font)
        self.name4.setObjectName("name4")
        self.name5 = QtWidgets.QLabel(self.centralwidget)
        self.name5.setGeometry(QtCore.QRect(590, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name5.setFont(font)
        self.name5.setObjectName("name5")
        self.name6 = QtWidgets.QLabel(self.centralwidget)
        self.name6.setGeometry(QtCore.QRect(690, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name6.setFont(font)
        self.name6.setObjectName("name6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name1.setText(_translate("MainWindow", "Alex"))
        self.name2.setText(_translate("MainWindow", "Clair"))
        self.name3.setText(_translate("MainWindow", "Tori"))
        self.day.setText(_translate("MainWindow", "Понеділок"))
        self.show.setText(_translate("MainWindow", "Показати відповідність вмісту нутріентів у дієті"))
        self.next.setText(_translate("MainWindow", "Наступний день"))
        self.prev.setText(_translate("MainWindow", "Попередній день"))
        self.name4.setText(_translate("MainWindow", "TextLabel"))
        self.name5.setText(_translate("MainWindow", "TextLabel"))
        self.name6.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
