# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\pythonProject\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from form2 import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Optimalfoodplan(object):
    def setupUi(self, Optimalfoodplan):
        Optimalfoodplan.setObjectName("Optimalfoodplan")
        Optimalfoodplan.resize(807, 581)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 210, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 210, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 210, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 210, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Optimalfoodplan.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Optimalfoodplan)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 681, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("проект1().png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 150, 231, 221))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("проект2.png"))
        self.label_2.setObjectName("label_2")
        self.begin_button = QtWidgets.QPushButton(self.centralwidget)
        self.begin_button.setGeometry(QtCore.QRect(230, 400, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(18)
        self.begin_button.setFont(font)
        self.begin_button.setStyleSheet("float:right;\n"
"margin-right: 3%;\n"
"margin top: 5px;\n"
"border-radius:5px;\n"
"-moz-border-radius:5px;\n"
"webkit-border-radius:5px;\n"
"padding:5px 9px;\n"
"font-size: 1.2em;\n"
"background-color:rgba(85, 184, 65,1);\n"
"text-shadow: #454545 0 0 2px;\n"
"border-bottom: 4px solid rgba(98, 193, 71, 1);\n"
"color:black;\n"
"font-family: \'Roboto Slab\', senif;")
        self.begin_button.setObjectName("begin_button")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(60, 160, 391, 211))
        self.textEdit.setAcceptDrops(True)
        self.textEdit.setObjectName("textEdit")
        Optimalfoodplan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Optimalfoodplan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 26))
        self.menubar.setObjectName("menubar")
        Optimalfoodplan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Optimalfoodplan)
        self.statusbar.setObjectName("statusbar")
        Optimalfoodplan.setStatusBar(self.statusbar)

        self.retranslateUi(Optimalfoodplan)
        QtCore.QMetaObject.connectSlotsByName(Optimalfoodplan)
    def Begin(self):
        ui2 = Ui_MainWindow()
        ui2.setupUi(MainWindow2)
        Optimalfoodplan.close()
        MainWindow2.show()


    def retranslateUi(self, Optimalfoodplan):
        _translate = QtCore.QCoreApplication.translate
        Optimalfoodplan.setWindowTitle(_translate("Optimalfoodplan", "Optimal food plan"))
        self.begin_button.setText(_translate("Optimalfoodplan", "Розпочати"))
        self.begin_button.clicked.connect(self.Begin)
        self.textEdit.setHtml(_translate("Optimalfoodplan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Це програма не є медичний протестованої. Якщо у вас є медичні протипоказання в плані харчування, проконсультуйтеся з вашим лікарем. Самолікування може бути шкідливим для вашого здоров\'я. Натиснувши кнопку «Розпочати», ви приймаєте на себе відповідальність за своє здоров\'я.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Optimalfoodplan = QtWidgets.QMainWindow()
    ui = Ui_Optimalfoodplan()
    ui.setupUi(Optimalfoodplan)
    Optimalfoodplan.show()
    sys.exit(app.exec_())
